DB_DRIVER=org.h2.Driver
DB_URL=jdbc:h2:file:/data/demo
DB_USER=sa
DB_PASSWORD=sa
DB_DDL=create-drop
KEYCLOAK_CLIENT_SECRET=test-secret
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false